// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transcoder.proto

package transcoder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	TargetFormat  string                 `protobuf:"bytes,2,opt,name=target_format,json=targetFormat,proto3" json:"target_format,omitempty"` // e.g., "mp4", "avi", "webp"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeRequest) Reset() {
	*x = TranscodeRequest{}
	mi := &file_transcoder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeRequest) ProtoMessage() {}

func (x *TranscodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeRequest.ProtoReflect.Descriptor instead.
func (*TranscodeRequest) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{0}
}

func (x *TranscodeRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *TranscodeRequest) GetTargetFormat() string {
	if x != nil {
		return x.TargetFormat
	}
	return ""
}

type TranscodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	OutputPath    string                 `protobuf:"bytes,3,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeResponse) Reset() {
	*x = TranscodeResponse{}
	mi := &file_transcoder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeResponse) ProtoMessage() {}

func (x *TranscodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeResponse.ProtoReflect.Descriptor instead.
func (*TranscodeResponse) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{1}
}

func (x *TranscodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TranscodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TranscodeResponse) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

var File_transcoder_proto protoreflect.FileDescriptor

const file_transcoder_proto_rawDesc = "" +
	"\n" +
	"\x10transcoder.proto\x12\n" +
	"transcoder\"T\n" +
	"\x10TranscodeRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12#\n" +
	"\rtarget_format\x18\x02 \x01(\tR\ftargetFormat\"h\n" +
	"\x11TranscodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\voutput_path\x18\x03 \x01(\tR\n" +
	"outputPath2b\n" +
	"\x11TranscoderService\x12M\n" +
	"\x0eStartTranscode\x12\x1c.transcoder.TranscodeRequest\x1a\x1d.transcoder.TranscodeResponseB;Z9github.com/Chintukr2004/video-transcoder/proto/transcoderb\x06proto3"

var (
	file_transcoder_proto_rawDescOnce sync.Once
	file_transcoder_proto_rawDescData []byte
)

func file_transcoder_proto_rawDescGZIP() []byte {
	file_transcoder_proto_rawDescOnce.Do(func() {
		file_transcoder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transcoder_proto_rawDesc), len(file_transcoder_proto_rawDesc)))
	})
	return file_transcoder_proto_rawDescData
}

var file_transcoder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transcoder_proto_goTypes = []any{
	(*TranscodeRequest)(nil),  // 0: transcoder.TranscodeRequest
	(*TranscodeResponse)(nil), // 1: transcoder.TranscodeResponse
}
var file_transcoder_proto_depIdxs = []int32{
	0, // 0: transcoder.TranscoderService.StartTranscode:input_type -> transcoder.TranscodeRequest
	1, // 1: transcoder.TranscoderService.StartTranscode:output_type -> transcoder.TranscodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transcoder_proto_init() }
func file_transcoder_proto_init() {
	if File_transcoder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transcoder_proto_rawDesc), len(file_transcoder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transcoder_proto_goTypes,
		DependencyIndexes: file_transcoder_proto_depIdxs,
		MessageInfos:      file_transcoder_proto_msgTypes,
	}.Build()
	File_transcoder_proto = out.File
	file_transcoder_proto_goTypes = nil
	file_transcoder_proto_depIdxs = nil
}
